require("config.set")
require("config.remap")
require("config.lazy")
require("config.colors")

vim.lsp.enable("ts")
vim.lsp.enable("lua")
vim.lsp.enable("css")
vim.lsp.enable("prisma")
vim.lsp.enable("tailwind")
