require("config.set")
require("config.remap")
require("config.lazy")
require("config.colors")

vim.lsp.enable("ts_ls")
vim.lsp.enable("lua_ls")
vim.lsp.enable("cssls")
vim.lsp.enable("prismals")
vim.lsp.enable("tailwindcss")
