vim.keymap.set("n", "<leader>nv", vim.cmd.Ex)
vim.keymap.set("n", "<leader>bd", ":%bd<CR>")
vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist)
vim.keymap.set("v" , "J" , ":m '>+1<CR>gv=gv")
vim.keymap.set("v" , "K" , ":m '<-2<CR>gv=gv")
